languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Antonio Patriarca"
copyright = ":copyright: 2024 Antonio Patriarca. All Rights Reserved."

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[author]
  name = "Antonio Patriarca"
  headline = "Senior Software Engineer"
  bio = "A little bit about you"
  links = [
    { email = "mailto:antoniopatriarca@gmail.com" },
    { github = "https://github.com/apatriarca" },
    { instagram = "https://www.instagram.com/antopatriarca/" },
    { linkedin = "https://www.linkedin.com/in/antonio-patriarca-27818a7/" },
    { mastodon = "https://mathstodon.xyz/@antopatriarca" },
  ]
